use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::parse::{SegmentKind, TopicInput};

pub fn generate(input: TopicInput) -> TokenStream {
    let name = &input.name;
    let key_name = format_ident!("{}Key", name);
    let name_str = name.to_string();
    let encoding = &input.encoding;
    let payload_name = &input.payload.name;
    let payload_ty = &input.payload.ty;

    let fields = &input.fields;
    let segments = &input.segments;

    let key_fields = fields.iter().map(|f| {
        let fname = &f.name;
        let fty = &f.ty;
        quote! { pub #fname: #fty }
    });

    let render_segments = segments.iter().map(|seg| match seg {
        SegmentKind::Literal(lit) => quote! {
            ::std::borrow::Cow::Borrowed(#lit)
        },
        SegmentKind::Dynamic(ident) => quote! {
            ::topik_core::__private::Segment::render(&self.#ident)
        },
    });

    let parse_stmts = segments.iter().enumerate().map(|(i, seg)| match seg {
        SegmentKind::Literal(lit) => quote! {
            match parts.get(#i) {
                Some(&#lit) => {}
                Some(got) => return Err(::topik_core::TopikError::LiteralMismatch {
                    position: #i,
                    expected: #lit.to_string(),
                    got: got.to_string(),
                }),
                None => return Err(::topik_core::TopikError::MissingSegment {
                    position: #i,
                    topic: topic.to_string(),
                }),
            }
        },
        SegmentKind::Dynamic(ident) => {
            let field_ty = fields
                .iter()
                .find(|f| f.name == *ident)
                .map(|f| &f.ty)
                .expect("segment field not found — should have been caught in parse.rs");
            quote! {
                let #ident = <#field_ty as ::topik_core::__private::Segment>::parse(
                    parts.get(#i).ok_or(::topik_core::TopikError::MissingSegment {
                        position: #i,
                        topic: topic.to_string(),
                    })?
                )?;
            }
        }
    });

    let key_field_names = fields.iter().map(|f| &f.name);

    let wildcard_segments = segments.iter().map(|seg| match seg {
        SegmentKind::Literal(lit) => quote! { #lit },
        SegmentKind::Dynamic(_) => quote! { single },
    });

    let from_key_fields = fields.iter().map(|f| {
        let fname = &f.name;
        quote! { #fname: key.#fname }
    });

    quote! {
        /// Key struct auto-generated by `#[derive(Topic)]`.
        /// Contains only topic path segments.
        /// Used internally by backends for deferred payload deserialization.
        #[doc(hidden)]
        #[derive(Debug, Clone)]
        pub struct #key_name {
            #(#key_fields,)*
        }

        impl ::topik_core::__private::Sealed for #name {}

        impl ::topik_core::Topic for #name {
            type Payload = #payload_ty;
            type Encoding = #encoding;
            const NAME: &'static str = #name_str;
        }

        impl ::topik_core::__private::TopicWire for #name {
            type Key = #key_name;

            fn render(&self, sep: char) -> String {
                [
                    #(#render_segments,)*
                ]
                .iter()
                .map(|s| s.as_ref())
                .collect::<Vec<&str>>()
                .join(&sep.to_string())
            }

            fn parse(
                topic: &str,
                sep: char,
            ) -> Result<Self::Key, ::topik_core::TopikError> {
                let parts: Vec<&str> = topic.split(sep).collect();
                #(#parse_stmts)*
                Ok(#key_name {
                    #(#key_field_names,)*
                })
            }

            fn from_key_and_payload(
                key: Self::Key,
                #payload_name: #payload_ty,
            ) -> Self {
                Self {
                    #(#from_key_fields,)*
                    #payload_name,
                }
            }

            fn wildcard_pattern(
                sep: char,
                single: &'static str,
                _multi: &'static str,
            ) -> String {
                [#(#wildcard_segments,)*]
                    .join(&sep.to_string())
            }

            fn payload(&self) -> &Self::Payload {
                &self.#payload_name
            }
        }
    }
}
