use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::parse::{SegmentKind, TopicEnumInput, TopicInput};

pub fn generate(input: TopicInput) -> TokenStream {
    let name = &input.name;
    let key_name = format_ident!("{}Key", name);
    let builder_name = format_ident!("{}SubscribeBuilder", name);
    let name_str = name.to_string();
    let encoding = &input.encoding;
    let payload_name = &input.payload.name;
    let payload_ty = &input.payload.ty;

    let fields = &input.fields;
    let segments = &input.segments;

    let key_fields = fields.iter().map(|f| {
        let fname = &f.name;
        let fty = &f.ty;
        quote! { pub #fname: #fty }
    });

    let render_segments = segments.iter().map(|seg| match seg {
        SegmentKind::Literal(lit) => quote! {
            ::std::borrow::Cow::Borrowed(#lit)
        },
        SegmentKind::Dynamic(ident) => quote! {
            ::topik_core::__private::Segment::render(&self.#ident)
        },
    });

    let parse_stmts = segments.iter().enumerate().map(|(i, seg)| match seg {
        SegmentKind::Literal(lit) => quote! {
            match parts.get(#i) {
                Some(&#lit) => {}
                Some(got) => return Err(::topik_core::TopikError::LiteralMismatch {
                    position: #i,
                    expected: #lit.to_string(),
                    got: got.to_string(),
                }),
                None => return Err(::topik_core::TopikError::MissingSegment {
                    position: #i,
                    topic: topic.to_string(),
                }),
            }
        },
        SegmentKind::Dynamic(ident) => {
            let field_ty = fields
                .iter()
                .find(|f| f.name == *ident)
                .map(|f| &f.ty)
                .expect("segment field not found");
            quote! {
                let #ident = <#field_ty as ::topik_core::__private::Segment>::parse(
                    parts.get(#i).ok_or(::topik_core::TopikError::MissingSegment {
                        position: #i,
                        topic: topic.to_string(),
                    })?
                )?;
            }
        }
    });

    let key_field_names = fields.iter().map(|f| &f.name);

    let wildcard_segments = segments.iter().map(|seg| match seg {
        SegmentKind::Literal(lit) => quote! { #lit },
        SegmentKind::Dynamic(_) => quote! { single },
    });

    let from_key_fields = fields.iter().map(|f| {
        let fname = &f.name;
        quote! { #fname: key.#fname }
    });

    let builder_fields = fields.iter().map(|f| {
        let fname = &f.name;
        let fty = &f.ty;
        quote! { pub #fname: Option<#fty> }
    });

    let builder_setters = fields.iter().map(|f| {
        let fname = &f.name;
        let fty = &f.ty;
        quote! {
            pub fn #fname(mut self, value: #fty) -> Self {
                self.#fname = Some(value);
                self
            }
        }
    });

    let builder_default_fields = fields.iter().map(|f| {
        let fname = &f.name;
        quote! { #fname: None }
    });

    let builder_pattern_segments = segments.iter().map(|seg| match seg {
        SegmentKind::Literal(lit) => quote! { #lit.to_string() },
        SegmentKind::Dynamic(ident) => quote! {
            match &self.#ident {
                Some(v) => ::topik_core::__private::Segment::render(v).into_owned(),
                None => single.to_string(),
            }
        },
    });

    quote! {
        /// Key struct auto-generated by `#[derive(Topic)]`.
        /// Contains only topic path segments.
        /// Used internally by backends for deferred payload deserialization.
        #[doc(hidden)]
        #[derive(Debug, Clone)]
        pub struct #key_name {
            #(#key_fields,)*
        }

        /// Subscribe builder auto-generated by `#[derive(Topic)]`.
        ///
        /// Pin specific segments to subscribe to a subset of messages.
        /// Unpinned segments become wildcards in the subscription pattern.
        ///
        /// Obtained via [`TopikClient::subscribe`].
        pub struct #builder_name {
            #(#builder_fields,)*
        }

        impl #builder_name {
            #(#builder_setters)*
        }

        impl ::topik_core::__private::SubscribeBuilder for #builder_name {
            fn build_pattern(&self, sep: char, single: &'static str) -> String {
                [
                    #(#builder_pattern_segments,)*
                ]
                .join(&sep.to_string())
            }
        }

        impl ::topik_core::__private::Sealed for #name {}

        impl ::topik_core::Topic for #name {
            type Payload = #payload_ty;
            type Encoding = #encoding;
            const NAME: &'static str = #name_str;
        }

        impl ::topik_core::__private::TopicWire for #name {
            type Key = #key_name;
            type SubscribeBuilder = #builder_name;

            fn render(&self, sep: char) -> String {
                [
                    #(#render_segments,)*
                ]
                .iter()
                .map(|s| s.as_ref())
                .collect::<Vec<&str>>()
                .join(&sep.to_string())
            }

            fn parse(
                topic: &str,
                sep: char,
            ) -> Result<Self::Key, ::topik_core::TopikError> {
                let parts: Vec<&str> = topic.split(sep).collect();
                #(#parse_stmts)*
                Ok(#key_name {
                    #(#key_field_names,)*
                })
            }

            fn from_key_and_payload(
                key: Self::Key,
                #payload_name: #payload_ty,
            ) -> Self {
                Self {
                    #(#from_key_fields,)*
                    #payload_name,
                }
            }

            fn wildcard_pattern(
                sep: char,
                single: &'static str,
                _multi: &'static str,
            ) -> String {
                [#(#wildcard_segments,)*]
                    .join(&sep.to_string())
            }

            fn payload(&self) -> &Self::Payload {
                &self.#payload_name
            }

            fn subscribe_builder() -> Self::SubscribeBuilder {
                #builder_name {
                    #(#builder_default_fields,)*
                }
            }
        }
    }
}

pub fn generate_topic_enum(input: TopicEnumInput) -> TokenStream {
    let name = &input.name;

    let pattern_arms = input.variants.iter().map(|v| {
        let ty = &v.topic_ty;
        quote! {
            <#ty as ::topik_core::__private::TopicWire>::wildcard_pattern(sep, single, multi)
        }
    });

    let try_parse_arms = input.variants.iter().map(|v| {
        let variant_name = &v.name;
        let ty = &v.topic_ty;
        quote! {
            if let Ok(key) = <#ty as ::topik_core::__private::TopicWire>::parse(topic, sep) {
                if let Ok(payload) = <#ty as ::topik_core::__private::TopicWire>::decode_payload(
                    ::bytes::Bytes::copy_from_slice(payload)
                ) {
                    return Ok(#name::#variant_name(
                        <#ty as ::topik_core::__private::TopicWire>::from_key_and_payload(key, payload)
                    ));
                }
            }
        }
    });

    quote! {
        impl ::topik_core::__private::TopicEnum for #name {
            fn patterns(sep: char, single: &'static str, multi: &'static str) -> Vec<String> {
                vec![
                    #(#pattern_arms,)*
                ]
            }

            fn try_from_raw(
                topic: &str,
                payload: &[u8],
                sep: char,
            ) -> Result<Self, ::topik_core::TopikError> {
                #(#try_parse_arms)*

                Err(::topik_core::TopikError::ParseError {
                    topic: topic.to_string(),
                    reason: "no variant matched".to_string(),
                })
            }
        }
    }
}
