use crate::encoding::Encoding;
use crate::error::TopikError;

/// Sealed trait pattern. Prevents external crates from implementing
/// [`TopicWire`] directly. The derive macro generates the necessary
/// `Sealed` impl alongside the `TopicWire` impl.
///
/// See: https://rust-lang.github.io/api-guidelines/future-proofing.html
mod private {
    pub trait Sealed {}
}

/// Core trait for typed pub/sub topics.
///
/// Derive this on a struct to define a typed topic. The derive macro
/// generates all segment rendering, parsing, and wildcard pattern logic.
///
/// # Example
///
/// ```rust
/// use topik::Topic;
///
/// #[derive(Topic)]
/// #[topic(segments("factory", "v2", device_id, kind))]
/// pub struct SensorReading {
///     pub device_id: u64,
///     pub kind: SensorKind,
///     #[payload]
///     pub data: TemperaturePayload,
/// }
/// ```
///
/// # Segments
///
/// The `segments(...)` attribute defines the ordered structure of the
/// topic string. String literals become fixed segments on the wire.
/// Field names reference struct fields which become dynamic typed segments.
///
/// The same definition renders correctly for every backend:
///
/// ```text
/// NATS  -> "factory.v2.42.temperature"
/// MQTT  -> "factory/v2/42/temperature"
/// Redis -> "factory:v2:42:temperature"
/// ```
///
/// # Payload
///
/// Mark exactly one field with `#[payload]` to bind the message body
/// to a typed value. The encoding is configurable via
/// `#[topic(encoding = ...)]` and defaults to JSON when the `json`
/// feature is enabled.
///
/// # Migration from legacy systems
///
/// For topics where the payload schema is not yet known, use
/// [`RawEncoding`](crate::encoding::RawEncoding) as a starting point:
///
/// ```rust
/// use topik::Topic;
/// use topik_core::encoding::RawEncoding;
/// use bytes::Bytes;
///
/// #[derive(Topic)]
/// #[topic(segments("legacy", "v1", device_id))]
/// #[topic(encoding = RawEncoding)]
/// pub struct LegacyTopic {
///     pub device_id: u64,
///     #[payload]
///     pub data: Bytes,
/// }
///
/// // once the schema is understood, swap the encoding and type the payload:
/// // #[topic(encoding = JsonEncoding)]
/// // pub data: SensorReading,
/// ```
pub trait Topic {
    /// The payload type carried by this topic.
    type Payload;

    /// The encoding used to serialize and deserialize the payload.
    type Encoding: Encoding<Self::Payload>;

    /// Human readable name for this topic type, derived from the struct name.
    ///
    /// Generated by the derive macro. Useful for logging and debugging
    /// without any extra user effort.
    ///
    /// ```rust
    /// assert_eq!(SensorReading::NAME, "SensorReading");
    /// ```
    const NAME: &'static str;
}

/// Internal trait used by backends to render and parse topic strings.
///
/// The [`Topic`] derive macro generates all implementations automatically.
/// Users never interact with this trait directly.
///
/// # For backend implementors
///
/// Backend crates access this through the `#[doc(hidden)]` re-export in
/// `topik`. When implementing a backend, use `TopicWire` to convert between
/// typed topics and the wire string format your broker expects.
///
/// ```rust
/// use topik::__private::TopicWire;
///
/// async fn publish<T: TopicWire>(
///     &self,
///     topic: &T,
///     payload: Bytes,
/// ) -> Result<(), TopikError> {
///     let wire = topic.render('.');  // NATS uses '.'
///     self.client.publish(wire, payload).await
/// }
/// ```
#[doc(hidden)]
pub trait TopicWire: Topic + private::Sealed {
    /// Render this topic instance to its wire string using the given separator.
    ///
    /// Called by backends when publishing.
    ///
    /// ```text
    /// SensorReading { device_id: 42, kind: Temperature }
    ///   .render('.')  ->  "factory.v2.42.temperature"
    ///   .render('/')  ->  "factory/v2/42/temperature"
    ///   .render(':')  ->  "factory:v2:42:temperature"
    /// ```
    fn render(&self, sep: char) -> String;

    /// Parse a raw topic string into this topic type.
    ///
    /// Called by backends when a message arrives.
    ///
    /// Returns `TopikError::LiteralMismatch` if a fixed segment doesn't match,
    /// `TopikError::MissingSegment` if the string is too short, and
    /// `TopikError::ParseError` if a dynamic segment fails to parse.
    fn parse(topic: &str, sep: char) -> Result<Self, TopikError>
    where
        Self: Sized;

    /// Generate the wildcard subscription pattern for this topic type.
    ///
    /// `single` and `multi` are the backend-specific wildcard tokens:
    ///
    /// | Backend | single | multi |
    /// |---------|--------|-------|
    /// | NATS    | `*`    | `>`   |
    /// | MQTT    | `+`    | `#`   |
    ///
    /// ```text
    /// SensorReading::wildcard_pattern('.', "*", ">")
    ///   →  "factory.v2.*.*"
    ///
    /// SensorReading::wildcard_pattern('/', "+", "#")
    ///   →  "factory/v2/+/+"
    /// ```
    fn wildcard_pattern(sep: char, single: &'static str, multi: &'static str) -> String;
}
