use crate::encoding::Encoding;
use crate::error::TopikError;
use crate::protocol::Protocol;
use crate::subscribe::SubscribeBuilder;

pub mod private {
    pub trait Sealed {}
}

pub trait Topic {
    /// The payload type carried by this topic.
    type Payload;

    /// The encoding used to serialize and deserialize the payload.
    type Encoding: Encoding<Self::Payload>;

    /// Human readable name for this topic type, derived from the struct name.
    ///
    /// ```ignore
    /// assert_eq!(SensorReading::NAME, "SensorReading");
    /// ```
    const NAME: &'static str;
}

/// Internal trait used by backends to render and parse topic strings.
///
/// Sealed: cannot be implemented outside of topik. The derive macro
/// generates all implementations.
#[doc(hidden)]
pub trait TopicWire: Topic + private::Sealed {
    /// Contains only the topic path segments.
    /// The backend can inspect and filter on topic segments before paying
    /// the cost of payload decoding.
    type Key;
    type SubscribeBuilder: SubscribeBuilder + Send + 'static;

    /// Render this topic instance to its wire string using the given separator.
    ///
    /// ```text
    /// SensorReading { device_id: 42, kind: Temperature }
    ///   .render('.')  ->  "factory.v2.42.temperature"
    ///   .render('/')  ->  "factory/v2/42/temperature"
    ///   .render(':')  ->  "factory:v2:42:temperature"
    /// ```
    fn render(&self, sep: char) -> String;

    /// Parse a raw topic string into the key type.
    ///
    /// Returns `TopikError::LiteralMismatch` if a fixed segment doesn't match,
    /// `TopikError::MissingSegment` if the string is too short, and
    /// `TopikError::ParseError` if a dynamic segment fails to parse.
    fn parse(topic: &str, sep: char) -> Result<Self::Key, TopikError>;

    /// Reconstruct the full topic struct from a parsed key and decoded payload.
    ///
    /// Called by backends after both parsing and payload decoding succeed.
    fn from_key_and_payload(key: Self::Key, payload: Self::Payload) -> Self;

    /// Generate the wildcard subscription pattern for this topic type.
    ///
    /// `single` and `multi` are backend-specific wildcard tokens:
    ///
    /// | Backend | single | multi |
    /// |---------|--------|-------|
    /// | NATS    | `*`    | `>`   |
    /// | MQTT    | `+`    | `#`   |
    ///
    /// ```text
    /// SensorReading::wildcard_pattern('.', "*", ">")
    ///   ->  "factory.v2.*.*"
    ///
    /// SensorReading::wildcard_pattern('/', "+", "#")
    ///   ->  "factory/v2/+/+"
    /// ```
    fn wildcard_pattern(sep: char, single: &'static str, multi: &'static str) -> String;

    /// Returns a reference to the payload field.
    /// Generated by the derive macro from the `#[payload]` field.
    fn payload(&self) -> &Self::Payload;

    /// Returns a subscribe builder for this topic type.
    /// All dynamic segments start as wildcards.
    fn subscribe_builder() -> Self::SubscribeBuilder;

    fn display<P: Protocol>(&self) -> TopicDisplay<'_, Self>
    where
        Self: Sized,
    {
        TopicDisplay {
            topic: self,
            sep: P::SEPARATOR,
        }
    }
}

pub struct TopicDisplay<'a, M: TopicWire> {
    topic: &'a M,
    sep: char,
}

impl<'a, M: TopicWire> std::fmt::Display for TopicDisplay<'a, M> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.topic.render(self.sep))
    }
}
