[package]
name = "topik-macros"
version = "0.2.0"
edition = "2024"
description = "Proc macros for topik"
license = "MIT"
repository = "https://github.com/railforge/topik"
rust-version = "1.88"

[lib]
proc-macro = true

[dependencies]
bytes = "1"
syn = { version = "3", features = ["full"] }
quote = "1"
proc-macro2 = "1"
topik-core = { version = "0.2", path = "../topik-core" }
