name: MSRV

on:
  pull_request:
    branches: [main]

jobs:
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.88
        uses: dtolnay/rust-toolchain@1.88

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check MSRV
        run: cargo check --workspace
